language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t paulcrashley/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true paulcrashley/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-176507503194"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
