    
version: '3.7'
services:    
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - 3000:3000
        volumes: 
            - /var/www/node_modules
            - .:/var/www
        stdin_open: true
